services:
  llm:
    image: vllm/vllm-openai:latest
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_VISIBLE_DEVICES=0
    command:
      [
        "/models/PhiLia093-LLM",
        "--trust-remote-code",
        "--language-model-only",
        "--served-model-name",
        "PhiLia093-LLM",
        "--max-model-len",
        "4096",
        "--max-num-seqs",
        "16",
        "--default-chat-template-kwargs",
        '{"enable_thinking": false}',
        "--gpu-memory-utilization",
        "0.80",
      ]
    ports:
      - "8001:8000"
    volumes:
      - "E:/Model:/models"
    ipc: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tts:
    image: vllm/vllm-omni:latest
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_VISIBLE_DEVICES=1
    command:
      [
        "vllm",
        "serve",
        "/models/PhiLia093-TTS",
        "--omni",
        "--trust-remote-code",
        "--served-model-name",
        "PhiLia093-TTS",
        "--max-model-len",
        "4096",
        "--max-num-seqs",
        "16",
        "--gpu-memory-utilization",
        "0.40",
      ]
    ports:
      - "8002:8000"
    volumes:
      - "E:/Model:/models"
    ipc: host
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
